spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9094
      bindings:
        messageConsumer-in-0:
          consumer:
            partitioned: true
            maxAttempts: 1
          group: kafkapingpong
          destination: ping
    function:
      definition: messageConsumer

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    connection-timeout: 5s

logging:
  level:
    ROOT: DEBUG