spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:${KAFKA_PORT}
      bindings:
        messageConsumer-input:
          consumer:
            partitioned: true
            maxAttempts: 1
          group: kafkapingpong
          destination: "ping"
        pong-output:
          producer:
            partitionKeyExpression: headers['partitionKey']
          destination: "pong"
          content-type: application/json
        pong-error-output:
          producer:
            partitionKeyExpression: headers['partitionKey']
          destination: "pong-error"
          content-type: application/json
        dlq-output:
          producer:
            partitionKeyExpression: headers['partitionKey']
          destination: "dlq"
          content-type: application/json

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    connection-timeout: 5s

logging:
  level:
    ROOT: INFO