spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:${KAFKA_PORT}
      bindings:
        messageConsumer-in-0:
          consumer:
            partitioned: true
            maxAttempts: 1
          group: kafkapingpong
          destination: "ping"
        pongSuccessProducer-out-0:
          destination: "pong"
        pongErrorProducer-out-0:
          destination: "pong-error"
        dlqProducer-out-0:
          destination: "dlq"
      function:
        definition: messageConsumer;pongSuccessProducer;pongErrorProducer;dlqProducer

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    connection-timeout: 5s

logging:
  level:
    ROOT: INFO