spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    connection-timeout: 5s

logging:
  level:
    ROOT: DEBUG